import type {
  Student,
  KPISummary,
  IPSTrendPoint,
  PopulationDataPoint,
} from "@/types";

// ─── Global campus IPS trend (Semester 1–8) ───────────────────────────────────
// Key finding: average IPS drops ~0.71 pts in Semesters 7–8
export const globalIPSTrend: IPSTrendPoint[] = [
  { semester: "Sem 1", avgIPS: 3.21 },
  { semester: "Sem 2", avgIPS: 3.15 },
  { semester: "Sem 3", avgIPS: 3.08 },
  { semester: "Sem 4", avgIPS: 2.98 },
  { semester: "Sem 5", avgIPS: 2.91 },
  { semester: "Sem 6", avgIPS: 2.85 },
  { semester: "Sem 7", avgIPS: 2.51 }, // ← sharp drop starts
  { semester: "Sem 8", avgIPS: 2.14 }, // ← ~0.71 drop from Sem 6
];

// ─── Mock students ────────────────────────────────────────────────────────────
export const mockStudents: Student[] = [
  {
    id: "1",
    nim: "S001",
    name: "Ahmad Fauzi",
    gender: "L",
    age: 22,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.5, 3.42, 3.38, 3.3, 3.25, 3.18, 3.1, 3.05],
    ipk: 3.27,
    riskScore: 15,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Teknik Informatika",
    entryYear: 2020,
  },
  {
    id: "2",
    nim: "S002",
    name: "Budi Santoso",
    gender: "L",
    age: 25,
    maritalStatus: "Married",
    employmentStatus: "Employed",
    ips: [3.2, 3.25, 3.18, 3.22, 3.15, 3.1, 2.45, 1.95],
    ipk: 2.94,
    riskScore: 88,
    riskLabel: "High",
    graduationStatus: "Late",
    hasIPSDegradation: true,
    program: "Sistem Informasi",
    entryYear: 2019,
  },
  {
    id: "3",
    nim: "S003",
    name: "Citra Dewi",
    gender: "P",
    age: 21,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.65, 3.58, 3.52, 3.46, 3.4, 3.35, 3.28, 3.2],
    ipk: 3.43,
    riskScore: 8,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Teknik Informatika",
    entryYear: 2021,
  },
  {
    id: "4",
    nim: "S004",
    name: "Dimas Prasetyo",
    gender: "L",
    age: 26,
    maritalStatus: "Married",
    employmentStatus: "Employed",
    ips: [3.3, 3.25, 3.2, 3.15, 3.1, 3.05, 2.3, 1.85],
    ipk: 2.9,
    riskScore: 92,
    riskLabel: "High",
    graduationStatus: "Late",
    hasIPSDegradation: true,
    program: "Manajemen Informatika",
    entryYear: 2018,
  },
  {
    id: "5",
    nim: "S005",
    name: "Eka Rahmawati",
    gender: "P",
    age: 22,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.4, 3.35, 3.28, 3.22, 3.18, 3.12, 3.05, 3.0],
    ipk: 3.2,
    riskScore: 18,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Sistem Informasi",
    entryYear: 2020,
  },
  {
    id: "6",
    nim: "S006",
    name: "Faisal Hidayat",
    gender: "L",
    age: 24,
    maritalStatus: "Single",
    employmentStatus: "Employed",
    ips: [2.95, 3.0, 2.9, 2.85, 2.8, 2.75, 2.2, 1.8],
    ipk: 2.78,
    riskScore: 85,
    riskLabel: "High",
    graduationStatus: "Late",
    hasIPSDegradation: true,
    program: "Teknik Informatika",
    entryYear: 2019,
  },
  {
    id: "7",
    nim: "S007",
    name: "Gita Purnama",
    gender: "P",
    age: 21,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.55, 3.48, 3.42, 3.36, 3.3, 3.25, 3.18, 3.1],
    ipk: 3.33,
    riskScore: 12,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Sistem Informasi",
    entryYear: 2021,
  },
  {
    id: "8",
    nim: "S008",
    name: "Hendra Kurniawan",
    gender: "L",
    age: 27,
    maritalStatus: "Married",
    employmentStatus: "Employed",
    ips: [3.1, 3.05, 2.98, 2.92, 2.85, 2.8, 2.15, 1.7],
    ipk: 2.82,
    riskScore: 90,
    riskLabel: "High",
    graduationStatus: "Late",
    hasIPSDegradation: true,
    program: "Manajemen Informatika",
    entryYear: 2017,
  },
  {
    id: "9",
    nim: "S009",
    name: "Indah Permata",
    gender: "P",
    age: 22,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.45, 3.38, 3.32, 3.25, 3.2, 3.15, 3.08, 3.0],
    ipk: 3.23,
    riskScore: 20,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Teknik Informatika",
    entryYear: 2020,
  },
  {
    id: "10",
    nim: "S010",
    name: "Joko Susanto",
    gender: "L",
    age: 23,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.0, 2.95, 2.9, 2.85, 2.8, 2.82, 2.75, 2.7],
    ipk: 2.85,
    riskScore: 35,
    riskLabel: "Medium",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Sistem Informasi",
    entryYear: 2020,
  },
  {
    id: "11",
    nim: "S011",
    name: "Kartika Sari",
    gender: "P",
    age: 22,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.6, 3.55, 3.5, 3.44, 3.38, 3.33, 3.25, 3.18],
    ipk: 3.4,
    riskScore: 10,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Teknik Informatika",
    entryYear: 2021,
  },
  {
    id: "12",
    nim: "S012",
    name: "Lukman Hakim",
    gender: "L",
    age: 24,
    maritalStatus: "Single",
    employmentStatus: "Employed",
    ips: [3.15, 3.1, 3.08, 3.05, 3.0, 2.98, 2.35, 1.9],
    ipk: 2.95,
    riskScore: 78,
    riskLabel: "High",
    graduationStatus: "Late",
    hasIPSDegradation: true,
    program: "Manajemen Informatika",
    entryYear: 2019,
  },
  {
    id: "13",
    nim: "S013",
    name: "Maya Putri",
    gender: "P",
    age: 21,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.48, 3.42, 3.36, 3.3, 3.24, 3.18, 3.12, 3.05],
    ipk: 3.27,
    riskScore: 14,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Sistem Informasi",
    entryYear: 2021,
  },
  {
    id: "14",
    nim: "S014",
    name: "Nanda Septian",
    gender: "L",
    age: 23,
    maritalStatus: "Single",
    employmentStatus: "Employed",
    ips: [2.85, 2.9, 2.88, 2.85, 2.8, 2.75, 2.1, 1.75],
    ipk: 2.74,
    riskScore: 82,
    riskLabel: "High",
    graduationStatus: "Late",
    hasIPSDegradation: true,
    program: "Teknik Informatika",
    entryYear: 2020,
  },
  {
    id: "15",
    nim: "S015",
    name: "Oktaviani",
    gender: "P",
    age: 24,
    maritalStatus: "Married",
    employmentStatus: "Employed",
    ips: [3.05, 3.0, 2.95, 2.9, 2.85, 2.8, 2.25, 1.88],
    ipk: 2.71,
    riskScore: 80,
    riskLabel: "High",
    graduationStatus: "Late",
    hasIPSDegradation: true,
    program: "Manajemen Informatika",
    entryYear: 2019,
  },
  {
    id: "16",
    nim: "S016",
    name: "Putri Rahayu",
    gender: "P",
    age: 21,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.55, 3.48, 3.42, 3.35, 3.28, 3.22, 3.15, 3.08],
    ipk: 3.32,
    riskScore: 11,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Teknik Informatika",
    entryYear: 2021,
  },
  {
    id: "17",
    nim: "S017",
    name: "Rizky Ramadhan",
    gender: "L",
    age: 22,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.3, 3.25, 3.2, 3.15, 3.1, 3.05, 3.0, 2.95],
    ipk: 3.13,
    riskScore: 22,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Sistem Informasi",
    entryYear: 2020,
  },
  {
    id: "18",
    nim: "S018",
    name: "Siti Nurhaliza",
    gender: "P",
    age: 22,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.42, 3.38, 3.32, 3.26, 3.2, 3.15, 3.08, 3.0],
    ipk: 3.23,
    riskScore: 16,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Teknik Informatika",
    entryYear: 2020,
  },
  {
    id: "19",
    nim: "S019",
    name: "Taufik Hidayat",
    gender: "L",
    age: 26,
    maritalStatus: "Married",
    employmentStatus: "Employed",
    ips: [3.0, 3.05, 2.98, 2.92, 2.88, 2.82, 2.2, 1.72],
    ipk: 2.82,
    riskScore: 87,
    riskLabel: "High",
    graduationStatus: "Late",
    hasIPSDegradation: true,
    program: "Manajemen Informatika",
    entryYear: 2018,
  },
  {
    id: "20",
    nim: "S020",
    name: "Umi Kalsum",
    gender: "P",
    age: 22,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.38, 3.32, 3.28, 3.22, 3.16, 3.1, 3.05, 2.98],
    ipk: 3.19,
    riskScore: 19,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Sistem Informasi",
    entryYear: 2020,
  },
  {
    id: "21",
    nim: "S021",
    name: "Wahyu Nugroho",
    gender: "L",
    age: 23,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [2.8, 2.75, 2.72, 2.68, 2.65, 2.6, 2.55, 2.5],
    ipk: 2.66,
    riskScore: 42,
    riskLabel: "Medium",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Sistem Informasi",
    entryYear: 2020,
  },
  {
    id: "22",
    nim: "S022",
    name: "Yuni Astuti",
    gender: "P",
    age: 23,
    maritalStatus: "Single",
    employmentStatus: "Employed",
    ips: [2.9, 2.95, 2.88, 2.82, 2.76, 2.7, 2.15, 1.85],
    ipk: 2.75,
    riskScore: 75,
    riskLabel: "High",
    graduationStatus: "Late",
    hasIPSDegradation: true,
    program: "Teknik Informatika",
    entryYear: 2020,
  },
  {
    id: "23",
    nim: "S023",
    name: "Zulfikar Ahmad",
    gender: "L",
    age: 24,
    maritalStatus: "Single",
    employmentStatus: "Employed",
    ips: [3.1, 3.05, 3.0, 2.95, 2.9, 2.85, 2.28, 1.92],
    ipk: 2.76,
    riskScore: 72,
    riskLabel: "High",
    graduationStatus: "Late",
    hasIPSDegradation: true,
    program: "Manajemen Informatika",
    entryYear: 2019,
  },
  {
    id: "24",
    nim: "S024",
    name: "Ayu Widyasari",
    gender: "P",
    age: 21,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.7, 3.65, 3.6, 3.55, 3.5, 3.45, 3.38, 3.3],
    ipk: 3.52,
    riskScore: 5,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Teknik Informatika",
    entryYear: 2021,
  },
  {
    id: "25",
    nim: "S025",
    name: "Bagas Wicaksono",
    gender: "L",
    age: 23,
    maritalStatus: "Single",
    employmentStatus: "Unemployed",
    ips: [3.25, 3.2, 3.15, 3.1, 3.05, 3.0, 2.95, 2.9],
    ipk: 3.08,
    riskScore: 25,
    riskLabel: "Low",
    graduationStatus: "On-Time",
    hasIPSDegradation: false,
    program: "Sistem Informasi",
    entryYear: 2020,
  },
];

// ─── Derived KPI summary ──────────────────────────────────────────────────────
export const kpiSummary: KPISummary = {
  totalStudents: mockStudents.length,
  predictedOnTime: mockStudents.filter((s) => s.graduationStatus === "On-Time")
    .length,
  predictedLate: mockStudents.filter((s) => s.graduationStatus === "Late")
    .length,
  highRiskCount: mockStudents.filter((s) => s.riskLabel === "High").length,
};

// ─── Population distributions (macro dataset of 120 students) ────────────────
export const ageDistribution: PopulationDataPoint[] = [
  { category: "≤21", onTime: 18, late: 2 },
  { category: "22", onTime: 28, late: 4 },
  { category: "23", onTime: 20, late: 8 },
  { category: "24", onTime: 8, late: 12 },
  { category: "≥25", onTime: 2, late: 18 },
];

export const employmentDistribution: PopulationDataPoint[] = [
  { category: "Unemployed", onTime: 70, late: 10 },
  { category: "Employed", onTime: 6, late: 34 },
];
